// 시도별 영문명, 한글명, 전체명 매핑
export const PROVINCE_NAMES: Record<number, string> = {
  1: '강원도',
  2: '경기도',
  3: '경상남도',
  4: '경상북도',
  5: '광주광역시',
  6: '대구광역시',
  7: '대전광역시',
  8: '부산광역시',
  9: '서울특별시',
  10: '세종특별자치시',
  11: '울산광역시',
  12: '인천광역시',
  13: '전라남도',
  14: '전북특별자치도',
  15: '제주특별자치도',
  16: '충청남도',
  17: '충청북도',
};

export const PROVINCE_NAME_ENGS: Record<number, string> = {
  1: 'gangwon',
  2: 'gyeonggi',
  3: 'gyeongnam',
  4: 'gyeongbuk',
  5: 'gwangju',
  6: 'daegu',
  7: 'daejeon',
  8: 'busan',
  9: 'seoul',
  10: 'sejong',
  11: 'ulsan',
  12: 'incheon',
  13: 'jeonnam',
  14: 'jeonbuk',
  15: 'jeju',
  16: 'chungnam',
  17: 'chungbuk',
};

export const PROVINCE_FULL_NAMES: Record<number, string> = {
  1: '강원특별자치도',
  2: '경기도',
  3: '경상남도',
  4: '경상북도',
  5: '광주광역시',
  6: '대구광역시',
  7: '대전광역시',
  8: '부산광역시',
  9: '서울특별시',
  10: '세종특별자치시',
  11: '울산광역시',
  12: '인천광역시',
  13: '전라남도',
  14: '전북특별자치도',
  15: '제주특별자치도',
  16: '충청남도',
  17: '충청북도',
}; 