import type { NextRequest } from 'next/server';
import { NextResponse } from 'next/server';

// 지역별 리디렉션 매핑
const regionRedirectMapping: Record<string, string> = {
  'seoul/jongro': '1',
  'seoul/junggu': '2',
  'seoul/yongsan': '3',
  'seoul/seongdong': '4',
  'seoul/gwangjin': '5',
  'seoul/dongdaemun': '6',
  'seoul/jungrang': '7',
  'seoul/seongbuk': '8',
  'seoul/gangbuk': '9',
  'seoul/dobong': '10',
  'seoul/nowon': '11',
  'seoul/eunpyeong': '12',
  'seoul/seodaemun': '13',
  'seoul/mapo': '14',
  'seoul/yangcheon': '15',
  'seoul/gangseo': '16',
  'seoul/guro': '17',
  'seoul/geumcheon': '18',
  'seoul/yeongdeungpo': '19',
  'seoul/dongjak': '20',
  'seoul/gwanak': '21',
  'seoul/seocho': '22',
  'seoul/gangnam': '23',
  'seoul/songpa': '24',
  'seoul/gangdong': '25',
  'busan/junggu': '26',
  'busan/seogu': '27',
  'busan/donggu': '28',
  'busan/yeongdo': '29',
  'busan/busanjin': '30',
  'busan/dongrae': '31',
  'busan/namgu': '32',
  'busan/bukgu': '33',
  'busan/haeundae': '34',
  'busan/saha': '35',
  'busan/geumjeong': '36',
  'busan/gangseo': '37',
  'busan/yeonje': '38',
  'busan/suyeong': '39',
  'busan/sasang': '40',
  'busan/gijang': '41',
  'daegu/junggu': '42',
  'daegu/donggu': '43',
  'daegu/seogu': '44',
  'daegu/namgu': '45',
  'daegu/bukgu': '46',
  'daegu/suseong': '47',
  'daegu/dalseo': '48',
  'daegu/dalseong': '49',
  'incheon/junggu': '50',
  'incheon/donggu': '51',
  'incheon/yeonsu': '52',
  'incheon/namdong': '53',
  'incheon/bupyeong': '54',
  'incheon/gyeyang': '55',
  'incheon/seogu': '56',
  'incheon/michuhol': '57',
  'incheon/ganghwa': '58',
  'incheon/ongjin': '59',
  'gwangju/donggu': '60',
  'gwangju/seogu': '61',
  'gwangju/namgu': '62',
  'gwangju/bukgu': '63',
  'gwangju/gwangsan': '64',
  'daejeon/donggu': '65',
  'daejeon/junggu': '66',
  'daejeon/seogu': '67',
  'daejeon/yuseong': '68',
  'daejeon/daedeok': '69',
  'ulsan/junggu': '70',
  'ulsan/namgu': '71',
  'ulsan/donggu': '72',
  'ulsan/bukgu': '73',
  'ulsan/ulju': '74',
  'sejong/sejong': '75',
  'gyeonggi/suwon': '76',
  'gyeonggi/seongnam': '77',
  'gyeonggi/uijeongbu': '78',
  'gyeonggi/anyang': '79',
  'gyeonggi/bucheon': '80',
  'gyeonggi/gwangmyeong': '81',
  'gyeonggi/pyeongtaek': '82',
  'gyeonggi/dongducheon': '83',
  'gyeonggi/ansan': '84',
  'gyeonggi/goyang': '85',
  'gyeonggi/gwacheon': '86',
  'gyeonggi/guri': '87',
  'gyeonggi/namyangju': '88',
  'gyeonggi/osan': '89',
  'gyeonggi/siheung': '90',
  'gyeonggi/gunpo': '91',
  'gyeonggi/uiwang': '92',
  'gyeonggi/hanam': '93',
  'gyeonggi/yongin': '94',
  'gyeonggi/paju': '95',
  'gyeonggi/icheon': '96',
  'gyeonggi/anseong': '97',
  'gyeonggi/gimpo': '98',
  'gyeonggi/hwaseong': '99',
  'gyeonggi/gwangju': '100',
  'gyeonggi/yangju': '101',
  'gyeonggi/pocheon': '102',
  'gyeonggi/yeoju': '103',
  'gyeonggi/yeoncheon': '104',
  'gyeonggi/gapyeong': '105',
  'gyeonggi/yangpyeong': '106',
  'gangwon/chuncheon': '107',
  'gangwon/wonju': '108',
  'gangwon/gangreung': '109',
  'gangwon/donghae': '110',
  'gangwon/taebaek': '111',
  'gangwon/sokcho': '112',
  'gangwon/samcheok': '113',
  'gangwon/hongcheon': '114',
  'gangwon/hoengseong': '115',
  'gangwon/yeongwol': '116',
  'gangwon/pyeongchang': '117',
  'gangwon/jeongseon': '118',
  'gangwon/cheolwon': '119',
  'gangwon/hwacheon': '120',
  'gangwon/yanggu': '121',
  'gangwon/inje': '122',
  'gangwon/goseong': '123',
  'gangwon/yangyang': '124',
  'chungbuk/chungju': '125',
  'chungbuk/jecheon': '126',
  'chungbuk/cheongju': '127',
  'chungbuk/boeun': '128',
  'chungbuk/okcheon': '129',
  'chungbuk/yeongdong': '130',
  'chungbuk/jincheon': '131',
  'chungbuk/goesan': '132',
  'chungbuk/eumseong': '133',
  'chungbuk/danyang': '134',
  'chungbuk/jeungpyeong': '135',
  'chungnam/cheonan': '136',
  'chungnam/gongju': '137',
  'chungnam/boryeong': '138',
  'chungnam/asan': '139',
  'chungnam/seosan': '140',
  'chungnam/nonsan': '141',
  'chungnam/geryong': '142',
  'chungnam/dangjin': '143',
  'chungnam/geumsan': '144',
  'chungnam/buyeo': '145',
  'chungnam/seocheon': '146',
  'chungnam/cheongyang': '147',
  'chungnam/hongseong': '148',
  'chungnam/yesan': '149',
  'chungnam/taean': '150',
  'jeonbuk/jeonju': '151',
  'jeonbuk/gunsan': '152',
  'jeonbuk/iksan': '153',
  'jeonbuk/jeongeup': '154',
  'jeonbuk/namwon': '155',
  'jeonbuk/gimje': '156',
  'jeonbuk/wanju': '157',
  'jeonbuk/jinan': '158',
  'jeonbuk/muju': '159',
  'jeonbuk/jangsu': '160',
  'jeonbuk/imsil': '161',
  'jeonbuk/sunchang': '162',
  'jeonbuk/gochang': '163',
  'jeonbuk/buan': '164',
  'jeonnam/mokpo': '165',
  'jeonnam/yeosu': '166',
  'jeonnam/suncheon': '167',
  'jeonnam/naju': '168',
  'jeonnam/gwangyang': '169',
  'jeonnam/damyang': '170',
  'jeonnam/gokseong': '171',
  'jeonnam/gurye': '172',
  'jeonnam/goheung': '173',
  'jeonnam/boseong': '174',
  'jeonnam/hwasun': '175',
  'jeonnam/jangheung': '176',
  'jeonnam/gangjin': '177',
  'jeonnam/haenam': '178',
  'jeonnam/yeongam': '179',
  'jeonnam/muan': '180',
  'jeonnam/hampyeong': '181',
  'jeonnam/yeonggwang': '182',
  'jeonnam/jangseong': '183',
  'jeonnam/wando': '184',
  'jeonnam/jindo': '185',
  'jeonnam/sinan': '186',
  'gyeongbuk/pohang': '187',
  'gyeongbuk/gyeongju': '188',
  'gyeongbuk/gimcheon': '189',
  'gyeongbuk/andong': '190',
  'gyeongbuk/gumi': '191',
  'gyeongbuk/yeongju': '192',
  'gyeongbuk/yeongcheon': '193',
  'gyeongbuk/sangju': '194',
  'gyeongbuk/mungyeong': '195',
  'gyeongbuk/gyeongsan': '196',
  'gyeongbuk/gunwi': '197',
  'gyeongbuk/uiseong': '198',
  'gyeongbuk/cheongsong': '199',
  'gyeongbuk/yeongyang': '200',
  'gyeongbuk/yeongdeok': '201',
  'gyeongbuk/cheongdo': '202',
  'gyeongbuk/goryeong': '203',
  'gyeongbuk/seongju': '204',
  'gyeongbuk/chilgok': '205',
  'gyeongbuk/yecheon': '206',
  'gyeongbuk/bonghwa': '207',
  'gyeongbuk/uljin': '208',
  'gyeongbuk/ulreung': '209',
  'gyeongnam/jinju': '210',
  'gyeongnam/tongyeong': '211',
  'gyeongnam/sacheon': '212',
  'gyeongnam/gimhae': '213',
  'gyeongnam/milyang': '214',
  'gyeongnam/geoje': '215',
  'gyeongnam/yangsan': '216',
  'gyeongnam/changwon': '217',
  'gyeongnam/uiryeong': '218',
  'gyeongnam/haman': '219',
  'gyeongnam/changnyeong': '220',
  'gyeongnam/goseong': '221',
  'gyeongnam/namhae': '222',
  'gyeongnam/hadong': '223',
  'gyeongnam/sancheong': '224',
  'gyeongnam/hamyang': '225',
  'gyeongnam/geochang': '226',
  'gyeongnam/hapcheon': '227',
  'jeju/jeju': '228',
  'jeju/seogwipo': '229',
};

export function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl;

  // /results/[province]/[region] 패턴 매칭
  const resultsMatch = pathname.match(/^\/results\/([^\/]+)\/([^\/]+)$/);

  if (resultsMatch) {
    const [, province, region] = resultsMatch;
    const key = `${province}/${region}`;
    const regionId = regionRedirectMapping[key];

    if (regionId) {
      return NextResponse.redirect(
        new URL(`/results/region/${regionId}`, request.url),
      );
    }
  }

  return NextResponse.next();
}

export const config = {
  matcher: ['/results/:path*'],
};
