name: Deploy Develop to EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. SSH 키 설정
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # 3. EC2 서버에 배포 스크립트 실행
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
            cd /home/ec2-user/k-laci && \
            git pull origin develop && \
            cd packages/backend && \
            NODE_OPTIONS='--max-old-space-size=512' yarn install --frozen-lockfile --network-timeout 100000 && \
            pm2 restart k-laci-backend || pm2 start yarn --name k-laci-backend --cwd /home/ec2-user/k-laci/packages/backend -- start:dev
          "
